spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sell?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

